---
# tasks file for apache
 
- apt: name={{ apache }} state=latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 
- service: name={{ apache }} state=restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- yum: name={{ httpd }} state=latest
  when: ansible_distribution == 'CentOS' 
- service: name={{ httpd }} state=restarted
  when: ansible_distribution == 'CentOS'
- import_tasks: configure.yml
